// Criando a primeira rota, para tornar o navegador do metodo POST
POST https://node-do-zero-c19r.onrender.com/videos 
// sempre em formato JSON para a API Rest
    // faz com que esse CONTEUDO seja do tipo JSON
Content-Type: application/json

 // Body 
{
    "title": "Video 1",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
// Busca

// Mostra Apenas o que tiver o nome no ?search=
GET https://node-do-zero-c19r.onrender.com/videos 
// GET http://localhost:3333/videos?search=node 


###
// Atualiza 
PUT https://node-do-zero-c19r.onrender.com/videos/2c44de46-9201-48fe-97d8-ab24b2c5df5d
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}
 
###
DELETE https://node-do-zero-c19r.onrender.com/videos/2c44de46-9201-48fe-97d8-ab24b2c5df5d
